version: '3.8'

services:
  web:
    image: docker-tut-web:latest
    build: ./app
    #build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      #- ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
